<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { listSkillFlowExecutions } from '../api/skillFlow';
import type { SkillFlowExecution } from '../types/skillFlow';
import SkillFlowExecutionDrawer from './SkillFlowExecutionDrawer.vue';

const executions = ref<SkillFlowExecution[]>([]);
const loading = ref(false); const error = ref(''); const status = ref(''); const keyword = ref(''); const page = ref(1); const pageSize = ref(20); const detailId = ref<number | null>(null); const detailOpen = ref(false);
const paged = computed(() => executions.value.slice((page.value - 1) * pageSize.value, page.value * pageSize.value));
let timer: ReturnType<typeof setInterval> | undefined;
function formatTime(value?: string | null) { return value ? value.replace('T', ' ').slice(0, 19) : '-'; }
function statusText(value: string) { return ({ WAITING_METRICS: '等待指标', QUEUED: '排队中', RUNNING: '执行中', SUMMARIZING: '汇总中', SUCCESS: '成功', PARTIAL_SUCCESS: '部分成功', FAILED: '失败', CANCELLED: '已取消', CANCEL_REQUESTED: '取消中' } as Record<string, string>)[value] || value; }
function duration(start?: string | null, end?: string | null) { if (!start || !end) return '-'; const seconds = Math.round((new Date(end).getTime() - new Date(start).getTime()) / 1000); return Number.isFinite(seconds) && seconds >= 0 ? (seconds < 60 ? `${seconds}s` : `${Math.floor(seconds / 60)}m${seconds % 60}s`) : '-'; }
async function load(silent = false) { if (!silent) loading.value = true; error.value = ''; try { executions.value = await listSkillFlowExecutions(status.value || undefined, keyword.value.trim() || undefined); page.value = 1; } catch (e) { error.value = e instanceof Error ? e.message : '加载长任务执行记录失败'; if (!silent) executions.value = []; } finally { loading.value = false; } }
function showDetail(id: number) { detailId.value = id; detailOpen.value = true; }
onMounted(() => { load(); timer = setInterval(() => { if (executions.value.some(item => ['WAITING_METRICS', 'QUEUED', 'RUNNING', 'SUMMARIZING', 'CANCEL_REQUESTED'].includes(item.status))) load(true); }, 5000); }); onUnmounted(() => { if (timer) clearInterval(timer); });
</script>

<template>
  <section><header class="page-header"><div><h2>长任务执行记录</h2><p>每行代表一个父任务，Skill 明细在详情中查看。</p></div><div class="actions"><input v-model="keyword" class="search" placeholder="搜索任务或原始问题" @keyup.enter="() => load()" /><select v-model="status" @change="() => load()"><option value="">全部状态</option><option value="WAITING_METRICS">等待指标</option><option value="QUEUED">排队中</option><option value="RUNNING">执行中</option><option value="SUCCESS">成功</option><option value="PARTIAL_SUCCESS">部分成功</option><option value="FAILED">失败</option><option value="CANCELLED">已取消</option></select><button class="btn" @click="() => load()">刷新</button></div></header><div v-if="error" class="error">{{ error }}</div><div v-if="loading" class="empty">加载中…</div><div v-else-if="!executions.length" class="empty">暂无长任务执行记录</div><div v-else class="table-wrap"><table><thead><tr><th>任务名称</th><th>状态</th><th>指标进度</th><th>Skill 进度</th><th>触发人</th><th>原始问题</th><th>创建时间</th><th>耗时</th><th>通知</th><th>操作</th></tr></thead><tbody><tr v-for="item in paged" :key="item.id"><td><strong>{{ item.flowName }}</strong><small>#{{ item.id }}</small></td><td><span class="status">{{ statusText(item.status) }}</span></td><td>{{ item.readyMetricCount }} / {{ item.requiredMetricCount }}</td><td>{{ item.completedNodeCount ?? 0 }} / {{ item.totalNodeCount ?? '-' }}</td><td>{{ item.triggerUserName || item.triggerUserId || '-' }}</td><td class="question" :title="item.originalQuestion">{{ item.originalQuestion || '-' }}</td><td class="time">{{ formatTime(item.createdAt) }}</td><td>{{ duration(item.startedAt, item.completedAt) }}</td><td>{{ item.latestNotificationStatus || '暂无记录' }}</td><td><button class="link-button" @click="showDetail(item.id)">查看详情</button><a v-if="item.reportUrl" :href="item.reportUrl" target="_blank" rel="noopener">查看报告</a></td></tr></tbody></table></div><div v-if="executions.length > pageSize" class="pagination"><el-pagination v-model:current-page="page" :page-size="pageSize" :page-sizes="[10, 20, 50]" :total="executions.length" layout="total, sizes, prev, pager, next" @size-change="(size: number) => { pageSize = size; page = 1; }" /></div><SkillFlowExecutionDrawer v-model:open="detailOpen" :execution-id="detailId" @changed="() => load(true)" /></section>
</template>

<style scoped>
.page-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin-bottom: 16px; flex-wrap: wrap; }.page-header h2 { margin: 0; color: #0f172a; font-size: 20px; }.page-header p { margin: 4px 0 0; color: #64748b; font-size: 13px; }.actions { display: flex; gap: 8px; flex-wrap: wrap; }.search, select { padding: 7px 10px; border: 1px solid #cbd5e1; border-radius: 6px; background: #fff; font: inherit; font-size: 13px; }.search { width: 210px; }.btn { padding: 7px 14px; border: 1px solid #cbd5e1; border-radius: 6px; background: #fff; color: #475569; cursor: pointer; font-size: 13px; }.table-wrap { overflow-x: auto; border-radius: 8px; box-shadow: 0 1px 3px rgb(0 0 0 / 6%); }table { width: 100%; min-width: 1200px; border-collapse: collapse; background: #fff; }th, td { padding: 10px 12px; border-bottom: 1px solid #e2e8f0; text-align: left; color: #334155; font-size: 13px; }th { background: #f8fafc; color: #475569; font-size: 12px; white-space: nowrap; }tr:hover td { background: #f8fafc; }td strong { display: block; color: #0f172a; }td small, .time { color: #94a3b8; font-size: 11px; }.question { max-width: 220px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.status { display: inline-block; padding: 2px 7px; border-radius: 4px; background: #eff6ff; color: #1d4ed8; font-weight: 700; font-size: 11px; white-space: nowrap; }.link-button, a { border: 0; background: transparent; color: #2563eb; cursor: pointer; font-size: 12px; padding: 0; text-decoration: none; }.link-button + a { margin-left: 8px; }.empty { padding: 48px 0; color: #94a3b8; text-align: center; font-size: 14px; }.error { margin-bottom: 12px; padding: 9px 12px; border-left: 3px solid #dc2626; background: #fef2f2; color: #b91c1c; font-size: 13px; }.pagination { display: flex; justify-content: flex-end; padding-top: 14px; }@media (max-width: 700px) { .actions { width: 100%; }.search { width: min(100%, 220px); } }
</style>
